### ISSUE TITLE
Using trigger events rather than callbacks

### ISSUE THREAD

**Issue by lski** [josedvq/colpick-jQuery-Color-Picker#10]
Hi

I love this picker so far, nice and clean. I just wanted to make the suggestion as to using triggers for the events rather than call back functions e.g. For the submit button being clicked the final line in the code below, using the 'colpick.' namespace:

clickSubmit = function (ev) {

```
            var cal = $(this).parent(),
                colpickObj = cal.data('colpick'),
                col = colpickObj.color,
                hex = hsbToHex(col),
                rgb = hsbToRgb(col);

            colpickObj.origColor = col;
            setCurrentColor(col, cal.get(0));

            colpickObj.onSubmit(col, hex, rgb, colpickObj.el);
            $(colpickObj.el).trigger('colpick.submit', [col, hex, rgb]);
        }
```

This is just a suggestion as I had to add it to work with my code, others might find it helpful.

Lee

**Comment by mrgrain** [comment]
See Issue https://github.com/josedvq/colpick-jQuery-Color-Picker/issues/1
