### ISSUE TITLE
CSS needs z-index

### ISSUE THREAD

**Issue by sargue** [josedvq/colpick-jQuery-Color-Picker#15]
I've found that the control, when used inside a BS3 modal, appears underneath it.

I have found that Bootstrap modal has a default z-index of 1050 so the colorpicker needs something higher to appear over modals.

I've set it to 10000 in my code because I think it should be in front of everything when it is invoked.

**Comment by mrgrain** [comment]
Not sure if this should be in the core of the plugin. For me e.g. it's enough to set a z-index of 1.
But the issue will be solved anyway, when the colopicker is appended inline instead to the body (see https://github.com/josedvq/colpick-jQuery-Color-Picker/pull/19)

**Comment by josedvq** [comment]
Should be fixed by now.
