### ISSUE TITLE
Major Bug with colpickShow()

### ISSUE THREAD

**Issue by Ganbin** [josedvq/colpick-jQuery-Color-Picker#17]
colpickShow() seems to not work anymore. I just try this plugin today and I cannot show it twice... Even if I use the main colorpick function to create it twice...

!!! Please Help !!!

**Comment by ideal123** [comment]
thanks, it works.

**Comment by moneypenny** [comment]
I'm still hitting this problem.

**Comment by ideal123** [comment]
Only add follow: 
if(ev) {
        ev.stopPropagation();
    }

**Comment by ideal123** [comment]
Only add the follow: 
if(ev) {
ev.stopPropagation();
}

**Comment by josedvq** [comment]
Thank you, had been fixed.
