### ISSUE TITLE
Keep color picker popup inside of window boundries?

### ISSUE THREAD

**Issue by seabasss** [josedvq/colpick-jQuery-Color-Picker#24]
Hey!

Thanks for an awesome plugin! Everything works great, except for when I open the color picker close to the bottom or right side of the page and the color picker disappears half way outside the window and there is no way to pick color and hit the submit button. Any suggestions to solve this? It would be great if it would adjust the position depending on how much space there is, or if that's difficult, extended the window when it's open.

Thanks!

**Comment by sibinx7** [comment]
I made a solution, I added some height and width related if condition, compare  height and width of color picker and height and width of window, then show it top,left,right and bottom accordingly...

**Comment by mrgrain** [comment]
@sibinx7 May you share the code with us? :)

**Comment by seabasss** [comment]
@sibinx7 yes, please share the code :)

**Comment by sibinx7** [comment]
Currently i don't have that piece of code but i will do it today evening...

**Comment by sibinx7** [comment]
True

**Comment by andrea-spotsoftware** [comment]
any news about it?

**Comment by sibinx7** [comment]
Open JS file and you can see 'show' function, you can set height, width, top, and bottom position... Do some calculation and set this top, left values..

**Comment by seabasss** [comment]
Is it possible to share the code you came up with sibinx7? Thanks!

**Comment by vivekpn** [comment]
By overriding onShow method. It worked for me.

```
$(this).colpick({
	layout: 'hex',
	color: #123456 //Color,
	onSubmit: function (hsb, hex, rgb, element) {
		// Function call on submit
	},
	onShow: function (colorDiv) {
		if (/*is colorpicker going out of the boundaries*/) {
			// Calculate the top and left pixels to which you want colorpiceker to come. 
			// And change the colordiv css properties
			$colorDiv.css('top', newTop + 'px');
		}
	}
})
```

**Comment by seabasss** [comment]
Got this part as well @vivekpn ? Thanks!

/*is colorpicker going out of the boundaries*/

**Comment by vivekpn** [comment]
@seabasss 
*/is colorpicker going out of the boundaries/*

The logic was not generic. It was specific to our code.

**Comment by seabasss** [comment]
Isn't there a way to check if it goes outside the browser window? That is same for everybody, or am I thinking wrong? Thanks! @vivekpn

**Comment by vivekpn** [comment]
@seabasss There must be some common way to do it I suppose! But I am not aware of it. Lets wait for others inputs.

**Comment by richardwillars** [comment]
I just wrote this. It doesn't do anything smart, just checks if the color picker is off the screen and if it is it moves it onto the screen. Ideally it should look at the position of the element that opened the color picker and move the color picker onto the opposite side of the element.

    onShow: function (colorDiv,e) {
        var $colorDiv = $(colorDiv);
        var div = {
            top: parseInt($colorDiv.css('top'), 10),
            left: parseInt($colorDiv.css('left'), 10)
        };
        div.right = div.left + $colorDiv.outerWidth();
        div.bottom = div.top + $colorDiv.outerHeight();

        var $win = $(window);
        var viewport = {
            top: $win.scrollTop(),
            left: $win.scrollLeft()
        };
        viewport.right = viewport.left + $win.width();
        viewport.bottom = viewport.top + $win.height();

        //if the colorpicker goes off the bottom of the viewport
        if(div.bottom>viewport.bottom) {
            div.top = div.top - $colorDiv.outerHeight();
            $colorDiv.css('top',div.top+'px');
        }
        //if the colorpicker goes off the right of the viewport
        if(div.right>viewport.right) {
            div.left = div.left - $colorDiv.outerWidth();
            $colorDiv.css('left',div.left+'px');
        }
    }

**Comment by seabasss** [comment]
@richardwillars Awesome! Works! Thanks!
