### ISSUE TITLE
This repo is not being updated

### ISSUE THREAD

**Issue by ansballard** [josedvq/colpick-jQuery-Color-Picker#26]
I've been watching this repo hoping the author would pop back in and merge some necessary pull requests, and even emailed him to see if he would allow someone else to, but I've gotten no response and it's been quite a while since his last comment. So does anyone have an updated fork that the current users could migrate to? This seems like a project that a few too many people use to be abandoned.

**Comment by mrgrain** [comment]
What about yours @ansballard? Or maybe @Boyyce?

**Comment by josedvq** [comment]
Back to it... will take care of the issues and push a variable-width version of the picker asap.
