### ISSUE TITLE
colpickShow causes javascript error

### ISSUE THREAD

**Issue by pergardebrink** [josedvq/colpick-jQuery-Color-Picker#30]
I have a small problem with the colpickShow function. When calling it, I get an error stating "Uncaught TypeError: Cannot read property 'stopPropagation' of undefined"

This seems to be because there is no event sent into the show function when called externally that it tries to use (on line 233 in colpick.js). Should there be some check if an event is provided before trying to stop propagation?

Example jsfiddle with the problem (open javascript console to see error): http://jsfiddle.net/uwwywjv8/

Great work btw!

**Comment by DorianListens** [comment]
I've encountered this problem as well, the way we've gotten around this is by using jQuery to fire a click event on the colpick target rather than running colpickShow, which has the same effect.

**Comment by moneypenny** [comment]
The color picker does not show when I do a `$('#picker').click()`.

**Comment by josedvq** [comment]
Fixed, thank you.
