### ISSUE TITLE
licensing question, no bug!

### ISSUE THREAD

**Issue by johnstonmatt** [josedvq/colpick-jQuery-Color-Picker#34]
Im not familiar with all licenses, but it is my understanding that if I include a reference to your contributions I could extend this to a web-component? I would be interested in collaborating with you using polymer if you would like, I think a cross-browser standard for color-pickers is important. Please close this and contact me by other means if this is not proper. Thanks!

**Comment by ansballard** [comment]
Sadly, this project hasn't been updated in quite a while, and I've tried without success to contact the author. Just wanted to comment in case he never gets back to you.

**Comment by mrgrain** [comment]
Yes you can! This project is dual licensed under the MIT and GPL licenses. So just include it into your project and don't forget to include reference to the original license.
