### ISSUE TITLE
OK button overflows outside border of popup

### ISSUE THREAD

**Issue by ajssd** [josedvq/colpick-jQuery-Color-Picker#40]
The Ok button should not be so close to the bottom of the popup.  The same margin below the large square and the slider should continue across below the OK button.  You never see an OK button right up against the bottom of the popup like this.  Can this be fixed?

![untitled](https://cloud.githubusercontent.com/assets/10245941/6046367/5f1d9da2-ac56-11e4-86a9-ce78e16a32c8.png)

**Comment by josedvq** [comment]
Not so easy to fix without making the picker larger, but will take it into account for future changes. It was made on purpose but I get your point, better to follow conventions.
