### ISSUE TITLE
init picker with current background color?

### ISSUE THREAD

**Issue by ottiauswien** [josedvq/colpick-jQuery-Color-Picker#42]
$("[picker='true']").colpick({  
color: $(this).css('background-color') 
}

wont work. whow can i start the picker with the color of the div it initialises?

**Comment by mrgrain** [comment]
It's not possible at the moment, you'll need two steps: (Code is untested)
```js
$("[picker='true']").colpick()
$("[picker='true']").each(function() {
  $(this).colpickSetColor($(this).css('background-color'));
});
```
