### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by radekdostal** [josedvq/colpick-jQuery-Color-Picker#46]
Please add this cool jQuery plugin to the [Bower](http://bower.io).

**Comment by mrgrain** [comment]
My [Fork](https://github.com/mrgrain/colpick) is available as package [jquery-colpick](http://bower.io/search/?q=jquery-colpick). All versions 2.* are identical to those here.

**Comment by radekdostal** [comment]
@mrgrain Thank you very much!
