### ISSUE TITLE
cannot set color inside color picker

### ISSUE THREAD

**Issue by nglatest** [josedvq/colpick-jQuery-Color-Picker#47]
I'm using two text boxes and color picker is attached to them. I want color picker to show color as per the current value of the respective input box. But it does not show anything.

My html code is like as:
<input type='text' class='color-field' name='one' />
<input type='text' class='color-field' name='two' />

and js code is like:
jQuery('color-field').colpick().change(function(){
            jQuery(this).colpickSetColor(this.val());
        });

I'm using it in wordpress. So please help me in this.

**Comment by GregWoods** [comment]
I think this fork deals with your issue, but I haven't tried it myself: https://github.com/mrgrain/colpick-jQuery-Color-Picker/blob/master/README.md

**Comment by josedvq** [comment]
Change is fired when the input element loses focus. It should update then. To update on every keystroke keyup, as per the example: http://codeitdown.com/colpick/plugin
